Add other architectures
conda-forge/unicorn-feedstock pull request #11
Opened 2023-06-01 17:57 UTC by pavelzw

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

2023-06-01 17:58 UTC, pavelzw commented
@conda-forge-admin, please rerender

2023-06-01 18:36 UTC, pavelzw commented
@conda-forge-admin, please rerender

2023-06-06 07:58 UTC, xhochy commented on recipe/meta.yaml
>    name: {{ name|lower }}
Let's start with this
```suggestion
  name: {{ name|lower }}-split
```

2023-06-06 07:58 UTC, xhochy commented on recipe/meta.yaml
>        host:
Please use  `- {{ pin_subpackage("unicorn", exact=True) }}` here in `host` and build`

2023-06-06 07:58 UTC, xhochy commented on recipe/meta.yaml
>  extra:
```suggestion
extra:
  feedstock-name: unicorn
```

2023-06-06 08:13 UTC, xhochy commented on recipe/build.sh
> +    ${CMAKE_ARGS} -LAH \
```suggestion
    ${CMAKE_ARGS} -LAH \
    -DCMAKE_C_COMPILER=${CC} \
    -DCMAKE_CXX_COMPILER=${CXX} \
```

2023-06-06 08:13 UTC, xhochy commented on recipe/build.sh
> +mkdir build
```suggestion
mkdir build

if [[ "${target_platform}" == linux-* ]]; then
  export LDFLAGS="-lrt ${LDFLAGS}"
fi
```

2023-06-06 08:13 UTC, xhochy commented on recipe/build.sh
> +    -DCMAKE_C_FLAGS=-lrt \
```suggestion
```

2023-06-06 08:13 UTC, xhochy commented on recipe/build.sh
>      -DCMAKE_INSTALL_LIBDIR=lib \
Part of `CMAKE_ARGS`
```suggestion
```

2023-06-08 19:28 UTC, pavelzw commented
@conda-forge-admin, please rerender

2023-06-09 08:03 UTC, pavelzw commented
@conda-forge-admin, please rerender

2023-06-09 08:18 UTC, pavelzw commented
@conda-forge-admin, please rerender

2023-06-11 14:37 UTC, 0xbe7a commented
@conda-forge-admin, please rerender

2023-06-11 15:29 UTC, pavelzw commented
Closes #7 
Closes #8 
Closes #9 
Closes #10

2023-06-11 18:41 UTC, xhochy requested changes
Don't use `python >=` on non-noarch packages.

2023-06-11 18:41 UTC, xhochy commented on recipe/meta.yaml
> +        - python >=3.6
```suggestion
        - python
```

2023-06-11 18:41 UTC, xhochy commented on recipe/meta.yaml
> +        - python >=3.6
```suggestion
        - python
```

2023-06-11 18:44 UTC, xhochy commented
@conda-forge-admin please rerender

2023-06-12 04:26 UTC, xhochy approved these changes
LGTM, leaving open for @chrisburr to review

2023-06-12 06:36 UTC, merged

2023-06-12 06:37 UTC, chrisburr commented
Thanks for updating this and thanks to @xhochy for reviewing! 🍰